### ISSUE TITLE
Missing Important Stock Trading Updates

### ISSUE THREAD

**Issue by fruithodler** [jmfernandes/robin_stocks#379]
I searched, but I didn't see any results regards to this error: "Your app version is missing important stock trading updates. You can still place orders on the web."

Does anyone know if this issue is already being aware and taken care of?

**Comment by GuitarGuyChrisB** [comment]
Following this issue. I'm encountering the same. Stock Market Buy orders are failing. Sell orders and Quotes are working. I have not attempted crypto transactions.

**Comment by schnup** [comment]
same here..

**Comment by mobeston** [comment]
Been daytrading with it every until today with this issue

**Comment by p1an3tz** [comment]
Same error. '.order_buy_fractional_by_price()' Doesn't seem to be working. And doesn't look to even exist in the documentation anymore.

**Comment by GuitarGuyChrisB** [comment]
The [documentation](https://robin-stocks.readthedocs.io/en/latest/robinhood.html) doesn't appear to have any references to any functions anymore. Is something going on with this library?

**Comment by jmfernandes** [comment]
Creator here. I just merged a few PRs and pushed a new 3.0.1 version to pip. Pip install the latest version and let me know if that fixes anything.

**Comment by p1an3tz** [comment]
Installed version 3.0.1 '.order_buy_fractional_by_price' still doesn't seem to be working.

**Comment by JaydenLong-Pseudo-SamCole** [comment]
For me it seems that when I try to buy a stock, in the helper.py, it's taking the 'gtc' or 'gfd' as the "price" variable, and throws the error:
**lib/python3.9/site-packages/robin_stocks/robinhood
/helper.py", line 157, in round_price
    price = float(price)
ValueError: could not convert string to float: 'gtc'**

This is the order: rh.order_buy_market('AAPL', 1)

**Comment by GuitarGuyChrisB** [comment]
Is it possible that Robinhood updated the expected user agent string/app identifier for a recent build of their client?

**Comment by fruithodler** [comment]
I'm not able to install 3.0.1 from command: pip install -U robin_stocks==3.0.1. 

Here's the error I get when I tried to install:
ERROR: Could not find a version that satisfies the requirement robin_stocks==3.0.1 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.8.1, 0.9.8.2, 0.9.8.3, 0.9.8.4, 0.9.8.5, 0.9.8.6, 0.9.8.7, 0.9.8.8, 0.9.9.0, 0.9.9.2, 0.9.9.3, 0.9.9.4, 0.9.9.5, 0.9.9.6, 1.0.0.0, 1.0.0.1, 1.0.0.2, 1.0.0.3, 1.0.0.4, 1.0.0.5, 1.0.0.6, 1.0.0.7, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0)
ERROR: No matching distribution found for robin_stocks==3.0.1

Did you install thru pip or manually?

**Comment by JaydenLong-Pseudo-SamCole** [comment]
> I'm not able to install 3.0.1 from command: pip install -U robin_stocks==3.0.1.
> 
> Here's the error I get when I tried to install: ERROR: Could not find a version that satisfies the requirement robin_stocks==3.0.1 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.8.1, 0.9.8.2, 0.9.8.3, 0.9.8.4, 0.9.8.5, 0.9.8.6, 0.9.8.7, 0.9.8.8, 0.9.9.0, 0.9.9.2, 0.9.9.3, 0.9.9.4, 0.9.9.5, 0.9.9.6, 1.0.0.0, 1.0.0.1, 1.0.0.2, 1.0.0.3, 1.0.0.4, 1.0.0.5, 1.0.0.6, 1.0.0.7, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.7.0, 1.7.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0) ERROR: No matching distribution found for robin_stocks==3.0.1
> 
> Did you install thru pip or manually?
> 
> Even manually, I couldn't find the release under: https://github.com/jmfernandes/robin_stocks/releases nor tags: https://github.com/jmfernandes/robin_stocks/tags I'll continue looking... will post once I make progress.

Just do "pip install robin_stocks," it'll automatically overwrite the old version with the new version, but just in case you can delete the old version in your Python library

**Comment by fruithodler** [comment]
Copy that. I was keeping safe by specifying the release 3.0.1 to make sure I get the said release with the potential fix. We'll find to hear from @jmfernandes

**Comment by erchen7** [comment]
the order call did not use the keyword to pass parameter. if you have issue with certain order type, make sure your parameter is with the same order of the function call. Hope next version will correct them all with keyword call.

example: 

order_buy_limit need to be changed from 

return order(symbol, quantity, "buy", limitPrice, None, timeInForce, extendedHours, jsonify)

to 

return order(symbol, quantity, "buy", None, limitPrice, None, timeInForce, extendedHours, jsonify)

**Comment by JaydenLong-Pseudo-SamCole** [comment]
Problem still persists for market orders, the program seems to think it should be given a 'price' in "rh.order_buy_market('AAPL', 1)" And doesn't submit the buy. It also doesn't work if I add a value like None or 0 for where it's looking for the 'price' attribute

**Comment by weijiazhang99** [comment]
fractional stock purchase stopped today but sell  is still working

**Comment by mobeston** [comment]
Before I begin RIP to the slack would be nice to revive that. I was able to record payload of manually placing a fractional order on the web. Reference pic. Seems like robinhood added a new order form version to the payload being expected with orders. I wasn't able to get it to work completely as there seems to be an issue with order quantity. Just note, they are also putting the fractional orders at 5% above last traded price(not a fan) but if we can get it working seems like we can adjust it in the request payload(yay). If anyone wants to take a look with the screenshots and try that would be nice, otherwise I'll find some time probably this weekend to reverse engineer whats missing. Thanks 
![robin1](https://github.com/jmfernandes/robin_stocks/assets/4539748/33651b85-ea5c-4282-ac5f-daf70f252f6e)
![image](https://github.com/jmfernandes/robin_stocks/assets/4539748/5f6f72c1-e0e0-4ef7-9ed2-3e6d6f8352fd)
![image](https://github.com/jmfernandes/robin_stocks/assets/4539748/8742e032-f3a1-489a-a255-fd43bfc2ea7b)

**Comment by fruithodler** [comment]
So in theory if we update the payload to include the missing 'order_form_version' and 'present_percent_limit' in the order(), inside orders.py, then it should work.

From:

```python
    payload = {
        'account': load_account_profile(account_number=account_number, info='url'),
        'instrument': get_instruments_by_symbols(symbol, info='url')[0],
        'symbol': symbol,
        'price': price,
        'quantity': quantity,
        'ref_id': str(uuid4()),
        'type': orderType,
        'stop_price': stopPrice,
        'time_in_force': timeInForce,
        'trigger': trigger,
        'side': side,
        'extended_hours': extendedHours
    }
``` 

To:

```python
    payload = {
        'account': load_account_profile(account_number=account_number, info='url'),
        'instrument': get_instruments_by_symbols(symbol, info='url')[0],
        'order_form_version': 2,
        'present_percent_limit': "0.05"
        'symbol': symbol,
        'price': price,
        'quantity': quantity,
        'ref_id': str(uuid4()),
        'type': orderType,
        'stop_price': stopPrice,
        'time_in_force': timeInForce,
        'trigger': trigger,
        'side': side,
        'extended_hours': extendedHours
    }
``` 

I will test it later.

**Comment by schnup** [comment]
typo 
*present => preset

**Comment by fruithodler** [comment]
> typo *present => preset

Thank you :)

**Comment by scurt8** [comment]
working... just add this to orders.py and install again...

    payload = {
    'account': load_account_profile(account_number=account_number, info='url'),
    'instrument': get_instruments_by_symbols(symbol, info='url')[0],
    'order_form_version': "2",
    'preset_percent_limit': "0.05",
    'symbol': symbol,
    'price': price,
    'quantity': fractional_shares,
    'ref_id': str(uuid4()),
    'type': "limit",
    'time_in_force': timeInForce,
    'trigger': "immediate",
    'side': "buy",
    'extended_hours': extendedHours
    }

    url = orders_url()
    data = request_post(url, payload, json=True, jsonify_data=jsonify)

    return (data)

**Comment by GuitarGuyChrisB** [comment]
Thanks, @scurt8! For my clarity, is this a function replacement for the **robin_stocks/robinhood/orders.py:order_buy_fractional_by_price** function? If so, can this be committed back to the main project?

**Comment by GuitarGuyChrisB** [comment]
Great, I got it working now, too with @scurt8 solution. I feel like this is a temporary solution until there's a way to pass multiple form versions to the @jmfernandes "order" function but this works for now.

Updated **robin_stocks/robinhood/orders.py** beginning on **Line 351** complete replacement for the **order_buy_fractional_by_price** function:

```
def order_buy_fractional_by_price(symbol, amountInDollars, account_number=None, timeInForce='gfd', extendedHours=False, jsonify=True):
    """Submits a market order to be executed immediately for fractional shares by specifying the amount in dollars that you want to trade.
    Good for share fractions up to 6 decimal places. Robinhood does not currently support placing limit, stop, or stop loss orders
    for fractional trades.

    :param symbol: The stock ticker of the stock to purchase.
    :type symbol: str
    :param amountInDollars: The amount in dollars of the fractional shares you want to buy.
    :type amountInDollars: float
    :param acccount_number: the robinhood account number.
    :type acccount_number: Optional[str]
    :param timeInForce: Changes how long the order will be in effect for. 'gfd' = good for the day.
    :type timeInForce: Optional[str]
    :param extendedHours: Premium users only. Allows trading during extended hours. Should be true or false.
    :type extendedHours: Optional[str]
    :param jsonify: If set to False, function will return the request object which contains status code and headers.
    :type jsonify: Optional[str]
    :returns: Dictionary that contains information regarding the purchase of stocks, \
    such as the order id, the state of order (queued, confired, filled, failed, canceled, etc.), \
    the price, and the quantity.

    """ 
    if amountInDollars < 1:
        print("ERROR: Fractional share price should meet minimum 1.00.", file=get_output())
        return None

    # turn the money amount into decimal number of shares
    price = next(iter(get_latest_price(symbol, 'ask_price', extendedHours)), 0.00)
    fractional_shares = 0 if (price == 0.00) else round_price(amountInDollars/float(price))
    
    ### ADDED FOR BUG FIX
    payload = {
        'account': load_account_profile(account_number=account_number, info='url'),
        'instrument': get_instruments_by_symbols(symbol, info='url')[0],
        'order_form_version': "2",
        'preset_percent_limit': "0.05",
        'symbol': symbol,
        'price': price,
        'quantity': fractional_shares,
        'ref_id': str(uuid4()),
        'type': "limit",
        'time_in_force': timeInForce,
        'trigger': "immediate",
        'side': "buy",
        'extended_hours': extendedHours
    }

    url = orders_url()
    data = request_post(url, payload, json=True, jsonify_data=jsonify)

    return (data)
    ### END OF ADDED FOR BUG FIX

    # return order(symbol, fractional_shares, "buy", account_number, None, None, timeInForce, extendedHours, jsonify)
```

**Comment by weijiazhang99** [comment]
Will it work if I reinstall robin_stocks package?

**Comment by jmfernandes** [comment]
@scurt8  can you make a PR?

**Comment by scurt8** [comment]
@jmfernandes i´m too new at this atm.... maybe @GuitarGuyChrisB can help!

**Comment by GuitarGuyChrisB** [comment]
I'm pretty new at this as well, but I'm willing to give it a shot.

**Comment by weijiazhang99** [comment]
when I added bug fix, I got a new error.
====
    'account': load_account_profile(account_number=account_number, info='url'),
NameError: name 'account_number' is not defined
 how to define "account_number"?
===

**Comment by GuitarGuyChrisB** [comment]
@weijiazhang99 account_number is passed in as part of the function call if you have multiple RH accounts (e.g. a brokerage and an IRA). It defaults to 'None' (which I believe defaults to the brokerage account).

def order_buy_fractional_by_price(symbol, amountInDollars, **account_number=None**, timeInForce='gfd', extendedHours=False, jsonify=True)

**Comment by evanbruno617** [comment]
Did this issue get fixed yet? Order still not working for me

**Comment by GuitarGuyChrisB** [comment]
> Did this issue get fixed yet? Order still not working for me

The PR isn't accepted and merged to the master yet. You can either download my fork or just manually make the change above to the code for now.

**Comment by weijiazhang99** [comment]
After  I updated python to 3.11, it worked.  I Thank you very much! 


Sent from Yahoo Mail for iPhone


On Thursday, May 25, 2023, 1:17 PM, GuitarGuyChrisB ***@***.***> wrote:




@weijiazhang99 account_number is passed in as part of the function call if you have multiple RH accounts (e.g. a brokerage and an IRA). It defaults to 'None' (which I believe defaults to the brokerage account).

def order_buy_fractional_by_price(symbol, amountInDollars, account_number=None, timeInForce='gfd', extendedHours=False, jsonify=True)

**Comment by JaydenLong-Pseudo-SamCole** [comment]
Regular order() and order_buy_market() are still faulty, I tried adding the payload bugfix element to those functions as well, but alass, did not work

**Comment by JaydenLong-Pseudo-SamCole** [comment]
I replaced the "order_buy_market" function with this, and got no errors. However, when I go to Robinhood no orders were sent:

@login_required
def order_buy_market(symbol, quantity, timeInForce='gtc', extendedHours=False, jsonify=True):

    try:
        symbol = symbol.upper().strip()
    except AttributeError as message:
        print(message, file=helper.get_output())
        return None

    price = round_price(next(iter(get_latest_price(symbol, "ask_price", extendedHours)), 0.00))
    print('ELLO')

    payload = {
        'account': load_account_profile(account_number='*whatever your account number is*', info='url'),
        'instrument': get_instruments_by_symbols(symbol, info='url')[0],
	'order_form_version': 2,
	'preset_percent_limit': "0.05",
        'symbol': symbol,
        'price': price,
        'quantity': quantity,
        'ref_id': str(uuid4()),
        'type': "limit",
        'time_in_force': "gfd",
        'trigger': "immediate",
        'side': "buy",
        'extended_hours': True
    }

    url = orders_url()
    data = request_post(url, payload, jsonify_data=jsonify)

    return(data)

**Comment by erchen7** [comment]
type is "limit" ?
I use buy_limit with ask_prices as an workaround

**Comment by erchen7** [comment]
it should be fixed from the order function not hard coded each order type.

**Comment by GuitarGuyChrisB** [comment]
Simply adding the new parameters to the order() function payload failed on sell orders. Apparently, buy orders are the only ones using the new form. It should be a matter of adding the new fields only for the buy side but not the sell side.

**Comment by fruithodler** [comment]
I added the new fields to the order payload but I'm getting this error: 

Error in request_post: Expecting value: line 1 column 1 (char 0)

Back up the hill...

**Comment by GuitarGuyChrisB** [comment]
I got it working for what appears to be most, if not all, orders with the following change to the **order** function in robin_stocks/robinhood/orders.py. I'm submitting a new PR now.

```
    payload = {
        'account': load_account_profile(account_number=account_number, info='url'),
        'instrument': get_instruments_by_symbols(symbol, info='url')[0],
        'symbol': symbol,
        'price': price,
        'quantity': quantity,
        'ref_id': str(uuid4()),
        'type': orderType,
        'stop_price': stopPrice,
        'time_in_force': timeInForce,
        'trigger': trigger,
        'side': side,
        'extended_hours': extendedHours
    }
    # BEGIN PATCH FOR NEW ROBINHOOD BUY FORM (GuitarGuyChrisB 5/26/2023)
    if side == "buy":
        payload['order_form_version'] = "2"
        payload['preset_percent_limit'] = "0.05"
    # END PATCH FOR NEW ROBINHOOD BUY FORM (GuitarGuyChrisB 5/26/2023)
```

**Comment by mobeston** [comment]
@GuitarGuyChrisB Seems like doesnt work for buy by fractional quantity for me, might be a but on how I use it but worked before

**Comment by erchen7** [comment]
I think the order_form_version won't cause issue on sell order, but  preset_percent_limit will

tested with sell_limt

**Comment by mobeston** [comment]
So many order types, was able to fix the issues I faced, which was order quantity error which the change I put on top of @GuitarGuyChrisB [here](https://github.com/mobeston/robin_stocks_order_issue_fix) fixes. Issue seemed to be limit vs market order type and accountnumber not being set in some order types causing cannot convert to float errors(saw some people had issues).

**Comment by fruithodler** [comment]
> So many order types, was able to fix the issues I faced, which was order quantity error which the change I put on top of @GuitarGuyChrisB [here](https://github.com/mobeston/robin_stocks_order_issue_fix) fixes. Issue seemed to be limit vs market order type and accountnumber not being set in some order types causing cannot convert to float errors(saw some people had issues).

I downloaded the changes you guys made and even tested my changes similar to the changes you guys made, but I'm getting th same error:

Error in request_post: Expecting value: line 1 column 1 (char 0)

Is anyone else having any luck?

**Comment by JaydenLong-Pseudo-SamCole** [comment]
I don't think Robinhood accepts type 'market' anymore. If you buy a stock
at market price on Robinhood itself, before you finalize the buy order, you
can see at the top that it's placing a "limit" order. Which is why the
payloads have changed

**Comment by fruithodler** [comment]
Thanks for the info. It appears to be the case. I will make the change and will submit a PR.

**Comment by eliwelch17** [comment]
So you are saying with this API you can no longer buy with fractional shares.. since limit orders do not allow for fractional shares?

**Comment by Adelantado** [comment]
Robinhood made some changes on their end so u will need to edit your orders.py as discussed in the tread to have fractional by price working again. Hopefully the bug_Fix will be implemented in a future revision.

    On Friday, June 9, 2023 at 04:24:31 PM EDT, eliwelch17 ***@***.***> wrote:  
 
 


So you are saying with this API you can no longer buy with fractional shares.. since limit orders do not allow for fractional shares?

**Comment by p1an3tz** [comment]
Did the fix and it looks to be giving me the error:

Exception has occurred: UnboundLocalError
local variable 'price' referenced before assignment

Anyone know where this could be coming from?

**Comment by Adelantado** [comment]
I would say that's a Python error, not Robin. Looks to me the variable "price" was not defined / assigned a value prior to be referenced ( called / utilized )

    On Wednesday, June 14, 2023 at 05:43:27 PM EDT, p1an3tz ***@***.***> wrote:  
 
 


Did the fix and it looks to be giving me the error:

Exception has occurred: UnboundLocalError
local variable 'price' referenced before assignment

Anyone know where this could be coming from?

**Comment by GuitarGuyChrisB** [comment]
The sell issue started again today even with the previous code fix in place. Seems RobinHood changed something yet again.

**Comment by schnup** [comment]
> Seems RobinHood changed something yet again.
> 
> I'm now getting the error from the **order_sell_fractional_by_quantity** function.
> 
> `{ "non_field_errors": [ "Your app version is missing important stock trading updates. You can still place orders on the web." ] } `

same here

**Comment by GuitarGuyChrisB** [comment]
I captured an updated sell order from the website:

`account: "_removed_"
check_overrides: []
extended_hours: false
instrument: "_removed_"
order_form_version: 2
quantity: "0.1"
ref_id: "_removed_"
side: "sell"
symbol: "CIBR"
time_in_force: "gfd"
trigger: "immediate"
type: "market"`

Looks like it's pretty much all about that 'order_form_version: 2' so I'll see what I can do. I hate to update another one-off function as it's not helping many folks and really not the best way to fix this.

**Comment by GuitarGuyChrisB** [comment]
I tested with this replacement for the **orders.py/order_sell_fractional_by_quantity** function. This is not a great solution, just a tested function, and it worked.

```
@login_required
def order_sell_fractional_by_quantity(symbol, quantity, account_number=None, timeInForce='gfd', priceType='bid_price', extendedHours=False, jsonify=True):
    """Submits a market order to be executed immediately for fractional shares by specifying the amount that you want to trade.
    Good for share fractions up to 6 decimal places. Robinhood does not currently support placing limit, stop, or stop loss orders
    for fractional trades.

    :param symbol: The stock ticker of the stock to purchase.
    :type symbol: str
    :param quantity: The amount of the fractional shares you want to buy.
    :type quantity: float
    :param acccount_number: the robinhood account number.
    :type acccount_number: Optional[str]
    :param timeInForce: Changes how long the order will be in effect for. 'gfd' = good for the day.
    :type timeInForce: Optional[str]
    :param extendedHours: Premium users only. Allows trading during extended hours. Should be true or false.
    :type extendedHours: Optional[str]
    :param jsonify: If set to False, function will return the request object which contains status code and headers.
    :type jsonify: Optional[str]
    :returns: Dictionary that contains information regarding the purchase of stocks, \
    such as the order id, the state of order (queued, confired, filled, failed, canceled, etc.), \
    the price, and the quantity.

    """
    ### ADDED FOR BUG FIX
    #return order(symbol, quantity, "sell", account_number, None, None, timeInForce, extendedHours, jsonify)
    
    payload = {
        'account': load_account_profile(account_number=account_number, info='url'),
        'instrument': get_instruments_by_symbols(symbol, info='url')[0],
        'order_form_version': "2",
        'symbol': symbol,
        'quantity': quantity,
        'ref_id': str(uuid4()),
        'type': "market",
        'time_in_force': timeInForce,
        'trigger': "immediate",
        'side': "sell",
        'extended_hours': extendedHours
    }

    url = orders_url()
    data = request_post(url, payload, json=True, jsonify_data=jsonify)

    return (data)
    ### END OF ADDED FOR BUG FIX
```

**Comment by scurt8** [comment]
def login is not working aswell... need to  replace the payload...  
payload = {
        'client_id': 'c82SH0WZOsabOXGP2sxqcj34FxkvfnWRZBKlBjFS',
        'expires_in': expiresIn,
        'order_form_version': "2",
        'grant_type': 'password',
        'password': password,
        'scope': scope,
        'username': username,
        'challenge_type': challenge_type,
        'device_token': device_token

on "authentication.py"

**Comment by scurt8** [comment]
def login is not working aswell..  need to add 'order_form_version': "2" on the payload...

**Comment by evanbruno617** [comment]
> > I tested with this replacement for the **robin_stocks/robinhood/orders.py:order_sell_fractional_by_quantity** function. This is not a great solution, just a tested function, and it worked.
> > ```
> > @login_required
> > def order_sell_fractional_by_quantity(symbol, quantity, account_number=None, timeInForce='gfd', priceType='bid_price', extendedHours=False, jsonify=True):
> >     """Submits a market order to be executed immediately for fractional shares by specifying the amount that you want to trade.
> >     Good for share fractions up to 6 decimal places. Robinhood does not currently support placing limit, stop, or stop loss orders
> >     for fractional trades.
> > 
> >     :param symbol: The stock ticker of the stock to purchase.
> >     :type symbol: str
> >     :param quantity: The amount of the fractional shares you want to buy.
> >     :type quantity: float
> >     :param acccount_number: the robinhood account number.
> >     :type acccount_number: Optional[str]
> >     :param timeInForce: Changes how long the order will be in effect for. 'gfd' = good for the day.
> >     :type timeInForce: Optional[str]
> >     :param extendedHours: Premium users only. Allows trading during extended hours. Should be true or false.
> >     :type extendedHours: Optional[str]
> >     :param jsonify: If set to False, function will return the request object which contains status code and headers.
> >     :type jsonify: Optional[str]
> >     :returns: Dictionary that contains information regarding the purchase of stocks, \
> >     such as the order id, the state of order (queued, confired, filled, failed, canceled, etc.), \
> >     the price, and the quantity.
> > 
> >     """
> >     ### ADDED FOR BUG FIX
> >     #return order(symbol, quantity, "sell", account_number, None, None, timeInForce, extendedHours, jsonify)
> >     
> >     payload = {
> >         'account': load_account_profile(account_number=account_number, info='url'),
> >         'instrument': get_instruments_by_symbols(symbol, info='url')[0],
> >         'order_form_version': "2",
> >         'symbol': symbol,
> >         'quantity': quantity,
> >         'ref_id': str(uuid4()),
> >         'type': "market",
> >         'time_in_force': timeInForce,
> >         'trigger': "immediate",
> >         'side': "sell",
> >         'extended_hours': extendedHours
> >     }
> > 
> >     url = orders_url()
> >     data = request_post(url, payload, json=True, jsonify_data=jsonify)
> > 
> >     return (data)
> >     ### END OF ADDED FOR BUG FIX
> > ```
> 
> It worked! Don't know what's going on under the HOOD.

It has been working, the only issue is buy by fractional shares/quantity

**Comment by GuitarGuyChrisB** [comment]
@evanbruno617 The buy function has a replacement posted earlier in this thread by @scurt8

**Comment by Adelantado** [comment]
For what is worth the "BUG FIX" for buy_fractional_by_price has been working for me since implemented and did work for the last again today at market close.  Will report fyi if I encounter any issues on the sell side.

**Comment by Adelantado** [comment]
order_sell_fractional_by_quantity did not work for me today; order was totally ignored.

**Comment by GuitarGuyChrisB** [comment]
> order_sell_fractional_by_quantity did not work for me today; order was totally ignored.

The above function replacement has been working for me since yesterday. It appears that Robinhood is slowly transitioning several functions to a new form version. Going to have to tackle them function by function until there's something more complete in place.

**Comment by Adelantado** [comment]
Update: got order_sell_fractional_by_quantity to go thru and quered. Thanks again GuitarGuyChrisB

On the other hand order_sell_fractional_by_price is getting cancelled when placed; I am playing around with that one but so far no luck.

**Comment by Adelantado** [comment]
Got order_sell_fractional_by_price working by modifying py as follows:

#############################################################
    ### BEGIN: Patch for new Robinhood Order Form (GuitarGuyChrisB 6/17/2023)
    
    # return order(symbol, fractional_shares, "sell", account_number, None, None, timeInForce, extendedHours, jsonify)

    payload = {
        'account': load_account_profile(account_number=account_number, info='url'),
        'instrument': get_instruments_by_symbols(symbol, info='url')[0],
        'order_form_version': "2",
        'symbol': symbol,
        'price': price,
        'quantity': fractional_shares,
        'ref_id': str(uuid4()),
        'type': "market",
        'time_in_force': timeInForce,
        'trigger': "immediate",
        'side': "sell",
        'extended_hours': extendedHours
    }

    url = orders_url()
    data = request_post(url, payload, json=True, jsonify_data=jsonify)

    return (data)
    ### END of Patch for new Robinhood Order Form (GuitarGuyChrisB 6/17/2023)
    ###########################################################

**Comment by Adelantado** [comment]
I'll be loading robin-stocks 3.0.4 to a secondary machine and share the results.
Thanks Master Joshua for your dedication and commitment to this project, for all the work and effort.

**Comment by meldinman** [comment]
looks like `'order_form_version` is throwing an error: `Error in request_post: Expecting value: line 1 column 1 (char 0)`
changing it to a float: `'order_form_version': "2.0",` seems to fix that however I am now getting a new error:
```
{'non_field_errors': ['Your app version is missing important stock trading updates. You can still place orders on the web.']}
```
Trying to figure out how to solve this one...

**Comment by meldinman** [comment]
looks like changing `'type': from 'market' to 'limit'` worked. I see this was previously discussed above, I was able to still submit orders until today so I guess will have to change all instances of buy market to limit with limit price at ask....

**Comment by SingularityMan** [comment]
> looks like changing `'type': from 'market' to 'limit'` worked. I see this was previously discussed above, I was able to still submit orders until today so I guess will have to change all instances of buy market to limit with limit price at ask.... I have temporarily fixed this by changing the order function to always submit order with `side == 'buy'` as `orderType='limit'`
> 
> ```
> @login_required
> def order(symbol, quantity, side, limitPrice=None, stopPrice=None, account_number=None, timeInForce='gtc', extendedHours=False, jsonify=True):
>     """A generic order function.
> 
>     :param symbol: The stock ticker of the stock to sell.
>     :type symbol: str
>     :param quantity: The number of stocks to sell.
>     :type quantity: int
>     :param side: Either 'buy' or 'sell'
>     :type side: str
>     :param limitPrice: The price to trigger the market order.
>     :type limitPrice: float
>     :param stopPrice: The price to trigger the limit or market order.
>     :type stopPrice: float
>     :param account_number: the robinhood account number.
>     :type account_number: Optional[str]
>     :param timeInForce: Changes how long the order will be in effect for. 'gtc' = good until cancelled. \
>     'gfd' = good for the day.
>     :type timeInForce: str
>     :param extendedHours: Premium users only. Allows trading during extended hours. Should be true or false.
>     :type extendedHours: Optional[str]
>     :param jsonify: If set to False, function will return the request object which contains status code and headers.
>     :type jsonify: Optional[str]
>     :returns: Dictionary that contains information regarding the purchase or selling of stocks, \
>     such as the order id, the state of order (queued, confired, filled, failed, canceled, etc.), \
>     the price, and the quantity.
> 
>     """ 
>     try:
>         symbol = symbol.upper().strip()
>     except AttributeError as message:
>         print(message, file=get_output())
>         return None
> 
>     orderType = "market"
>     trigger = "immediate"
> 
>     if side == "buy":
>         priceType = "ask_price"
>         ### assert all buy orders are sent as limits else order will throw error.
>         orderType = 'limit' 
>     else:
>         priceType = "bid_price"
> 
>     if limitPrice and stopPrice:
>         price = round_price(limitPrice)
>         stopPrice = round_price(stopPrice)
>         orderType = "limit"
>         trigger = "stop"
>     elif limitPrice:
>         price = round_price(limitPrice)
>         orderType = "limit"
>     elif stopPrice:
>         stopPrice = round_price(stopPrice)
>         if side == "buy":
>             price = stopPrice
>         else:
>             price = None
>         trigger = "stop"
>     else:
>         price = round_price(next(iter(get_latest_price(symbol, priceType, extendedHours)), 0.00))
>     payload = {
>         'account': load_account_profile(account_number=account_number, info='url'),
>         'instrument': get_instruments_by_symbols(symbol, info='url')[0],
>         'order_form_version': "2.0",
>         'symbol': symbol,
>         'price': price,
>         'quantity': quantity,
>         'ref_id': str(uuid4()),
>         'type': orderType,
>         'stop_price': stopPrice,
>         'time_in_force': timeInForce,
>         'trigger': trigger,
>         'side': side,
>         'extended_hours': extendedHours
>     }
>     # BEGIN PATCH FOR NEW ROBINHOOD BUY FORM (GuitarGuyChrisB 5/26/2023)
>     if side == "buy":
>         payload['preset_percent_limit'] = "0.05"
>     # END PATCH FOR NEW ROBINHOOD BUY FORM (GuitarGuyChrisB 5/26/2023)
>     url = orders_url()
> 
> 
>     data = request_post(url, payload, jsonify_data=jsonify)
> 
>     return(data)
> ```

Your code seems to work for my purposes, both buying and selling fractional shares. However, you do need to round out your fractional share amount before submitting the order because you will receive an error message. I use floor() for this but it seems to work on my end. Thanks!

**Comment by Adelantado** [comment]
Any input on this one would be greatly appreciated as I can not make sense  of what just happened today:
Just before market close an order_sell_fractional_by_quantity  ( extendedHours=False) was totally ignored, no errors, no messages, no nothing.
I just run the same code ( market is close now ) and order went thru and got queued.

Have no idea whats going on.

**Comment by NelsonDane** [comment]
Any updates on this? I'm still facing this issue which makes the entire API unusable for my use case
