### ISSUE TITLE
challenge_response["status"] : {'detail': 'Authentication credentials were not provided.'}

### ISSUE THREAD

**Issue by helhadry** [jmfernandes/robin_stocks#523]
Hello,

I'm using the fix from this PR for robin authentication :
https://github.com/jmfernandes/robin_stocks/pull/510

It was working fine but now I don't receive the SMS code and It's failing at this point:
`challenge_response = request_post(url=challenge_url, payload=challenge_payload, json=True)

      if challenge_response["status"] == "validated":
          inquiries_payload = {"sequence": 0, "user_input": {"status": "continue"}}`

here is what I see in the challenge_response (there is no status in the dictionary):
{'detail': 'Authentication credentials were not provided.'}

Thanks for your help.

**Comment by Two20Two21** [comment]
Me too.

**Comment by No-Reality-Shows** [comment]
me three

**Comment by Two20Two21** [comment]
I used the code below with the latest robin-stocks release (3.2.1) plus the authentication.py module from two weeks ago with the sheriff module and it no longer works for me. It doesn't prompt me for the MFA code, it just errors out.

MY CODE
======
import robin_stocks.robinhood
import pyotp
from datetime import *

now = datetime.now()
totp = pyotp.TOTP("KACUJH6EKZZCVZ6K").now()
print("TOTP: " + str(totp))
login = robin_stocks.robinhood.login(my_user_name, my_password, store_session=True)

**Comment by Two20Two21** [comment]
Bonehead move on my part.  Got the MFA code from the authenticator app.  Didn't enter the six digit code.  I'm running.  Thanks for your help.

**Comment by regholl2023** [comment]
it says i get the TOTP FROM MY ROBINHOOD ACCOUNT SETTINGS BUT I CAN'T FIND IT

**Comment by Two20Two21** [comment]
If you look at the code I have above, it will print the ToTP code to the console.  Here's a tutorial if that helps.  https://www.youtube.com/watch?v=C5buU4zjjx0

**Comment by regholl2023** [comment]
I followed the video and this was the output, ERROR: There was an issue loading pickle file. Authentication may be expired - logging in normally.
Traceback (most recent call last):
  File "E:\ROBINHOOD\robin.py", line 7, in <module>
    login = rh.login('regholl1968@gmail.com','001Primo$$')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ROBINHOOD\venv\Lib\site-packages\robin_stocks\robinhood\authentication.py", line 190, in login
    _validate_sherrif_id(device_token=device_token, workflow_id=workflow_id, mfa_code=mfa_code)
  File "E:\ROBINHOOD\venv\Lib\site-packages\robin_stocks\robinhood\authentication.py", line 230, in _validate_sherrif_id
    if challenge_response["status"] == "validated":
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'status'

**Comment by Two20Two21** [comment]
Have you looked at this?  https://github.com/jmfernandes/robin_stocks/pull/510

**Comment by regholl2023** [comment]
nope,I followed the vid exactly but i shall have a look now ty.

**Comment by nat2k5us** [comment]
> nope,I followed the vid exactly but i shall have a look now ty.

You should delete the passed you posted and also change it

**Comment by Two20Two21** [comment]
What?

**Comment by nat2k5us** [comment]
> File "E:\ROBINHOOD\robin.py", line 7, in
> login = rh.login('[regholl1968@gmail.com](mailto:regholl1968@gmail.com)','001Primo$$')

**Comment by regholl2023** [comment]
ty,i was so frustrated didn't even think about that.

**Comment by regholl2023** [comment]
i'm getting error in authentication.py,"data" is not defined

**Comment by nat2k5us** [comment]
> i'm getting error in authentication.py,"data" is not defined in the def _get_sherrif_challenge
have you tried?
https://github.com/jmfernandes/robin_stocks/issues/524#issuecomment-2558513971

**Comment by regholl2023** [comment]
fixed that now im on "validate_sheriff_url" is not defined error in authentication.py

**Comment by hokeihero** [comment]
I have the same issue [{'detail': 'Authentication credentials were not provided.'}] and the Robinhood app have prompt ask me if I am logging in. Even I clicked yes, the process is still failed.
